version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused

  exclusions:
    rules:
      - path: e2e/
        linters:
          - depguard
      # Exclude var-naming.
      - linters:
          - revive
        text: var-naming

  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/oasisprotocol/rofl-app-backend
            - github.com/oasisprotocol/oasis-sdk/client-sdk/go
            - github.com/ethereum/go-ethereum/accounts/abi
            - github.com/ethereum/go-ethereum/common
            - github.com/ethereum/go-ethereum/crypto
            - github.com/go-chi/chi/v5
            - github.com/go-chi/cors
            - github.com/go-chi/httplog/v3
            - cloud.google.com/go/storage
            - github.com/golang-jwt/jwt/v5
            - github.com/hibiken/asynq
            - github.com/knadh/koanf
            - github.com/prometheus/client_golang/prometheus
            - github.com/redis/go-redis/v9
            - github.com/spf13/cobra
            - github.com/spruceid/siwe-go
            - golang.org/x/net/context/ctxhttp
            - google.golang.org/api/option
          deny:
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
    gosec:
      excludes:
        - G402
        - G404
        - G115
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/oasisprotocol/rofl-app-backend
