name: rofl-app-backend

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - fakegcs
    volumes:
      - ./docker/config-api.yml:/app/config-api.yml:ro
    command: ["--config", "/app/config-api.yml"]
    ports:
      - "127.0.0.1:8899:8899"

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./docker/config-worker.yml:/app/config-worker.yml:ro
    command: ["--config", "/app/config-worker.yml"]

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"

  fakegcs:
      image: fsouza/fake-gcs-server:latest
      ports:
        - "127.0.0.1:4443:4443"
      entrypoint:
        - /bin/sh
        - -c
        - |
          # Initialize the bucket that's expected by the app.
          mkdir -p /data/rofl-app-backend && \
            exec /bin/fake-gcs-server \
              -scheme=http \
              -host=0.0.0.0 \
              -port=4443 \
              -public-host=fakegcs:4443 \
              -data=/data

  # TODO: Uncomment if you want to run prometheus as well.
  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - "127.0.0.1:9090:9090"
  #   depends_on:
  #     - app
