name: mock # This name appears in GitHub's Checks API and in workflow's status badge.

# THIS WORKFLOW:
#   Is special, and only a workaround for limitations in Github's CI config.
#   When a PR touches only changelog .md files, most CI workflows do not run.
#   However, our branch protection rules still require that the jobs in those
#   workflows _pass_; them being skipped is not good enough for Github.
#
#   This workflow creates mock success statuses for all the jobs that would
#   otherwise run in regular CI workflows, and triggers exactly when the regular
#   CI workflows don't.

on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - master
    paths: # Trigger if _only_ these files were changed.
      - .punch_version.py
      - .changelog/*.md
      - CHANGELOG.md
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - master
    paths: # Trigger if _only_ these files were changed.
      - .punch_version.py
      - .changelog/*.md
      - CHANGELOG.md

permissions:
  contents: read

jobs:
  build-go:
    name: build-go
    runs-on: ubuntu-latest
    steps: [{name: "fake success", run: "exit 0"}]
  lint-go:
    name: lint-go
    runs-on: ubuntu-latest
    steps: [{name: "fake success", run: "exit 0"}]
  test-e2e:
    name: test-e2e
    runs-on: ubuntu-latest
    steps: [{name: "fake success", run: "exit 0"}]
